### ISSUE TITLE
[4pts] Create Food list (Student A)

### ISSUE THREAD

**Issue by sebalp100** [enoqueJonas/recepe-ror#3]
Create a Food list page:

![Image](https://github.com/microverseinc/curriculum-rails/raw/main/recipe-app/images/food_index.png)

- Should display a list of food added by the logged-in user as in the wireframe (for teams with only 2 people - display also quantity of a given food).
- Should lead to a form that allows users to add new food.

**Comment by enoqueJonas** [comment]
Hello @sebalp100. Here's the [link](https://github.com/enoqueJonas/recepe-ror/pull/15) to the PR.
