### ISSUE TITLE
[4pts] Create a Public recipe list page (Student A)

### ISSUE THREAD

**Issue by sebalp100** [enoqueJonas/recepe-ror#5]
![Image](https://github.com/microverseinc/curriculum-rails/raw/main/recipe-app/images/public_recipe_index.png)

Create a public recipes list:

- Should display a list of all public recipes ordered by the newest as in the wireframe.
- Should lead to recipe details.

**Comment by enoqueJonas** [comment]
[Here](https://github.com/enoqueJonas/recepe-ror/pull/17) you will find the link to the PR.
